name: CI

on: [push]

jobs: 
    build: 
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code 
            uses: actions/checkout@v4
        - name: Viewing files
            run: ls -la
        - name: Viewing files
            run: cat test-file-1.txt
        